### ISSUE TITLE
"make dist" fails when more than one mstc-astros image tag exists

### ISSUE THREAD

**Issue by marcodlk** [dreedyman/mstc-web-astros#1]
## Expected Behavior
Run `make dist` successfully, even when multiple versions of "mstc-astros" images exist.

## Current Behavior
If more than one "mstc-astros:*" docker image exists, running `make dist` results in the following error:
```
$ make dist
/bin/sh: line 0: [: mstc-astros:0.2.0: binary operator expected
/bin/sh: line 0: [: too many arguments
```

## Possible Solution
Update the IMAGE variable definition in Makefile.
```Makefile
IMAGE := $(shell docker images | grep $(IMAGE_NAME) | awk 'NR==1{print $$1":"$$2}')
```

## Steps to Reproduce
1. Pull latest main branch.
2. Create a new tag for existing "mstc-astros" image (if only one exists), i.e. `docker tag mstc-astros:0.2.0 mstc-astros:9.9.9`
3. Run `make dist`.

**Comment by dreedyman** [comment]
Nice report, thanks.  Fix has been made and pushed.
