### ISSUE TITLE
The current Provider+DataService design may be incompatible with Kubernetes

### ISSUE THREAD

**Issue by marcodlk** [dreedyman/mstc-web-astros#3]
## Description
The current design relies on the DataService hostname being resolvable by the DataService client on the other end. In the Kubernetes context, the hostnames of containers in a pod are not resolvable by other containers, even within the cluster. This means that the output urls returned by the Astros provider in a pod cannot be resolved by an Astros client outside of the pod (inside or outside the cluster).

Consider we have:
- Pod "mstc-astros-pod999" running Astros provider with rest port 8080 and data port 8081.
- Service "mstc-astros-svc" maps rest port to nodePort 31001 and data port to nodePort 31002.
- Host machine with hostname "mypc.local" runs Astros client with data port 49428

What happens:
1) Astros client calls "exec" endpoint (using nodePort) and passes input urls using hostname "mypc.local"
2) Astros provider successfully transfers files from "http://mypc.local:49428/..." because it can resolve the host hostname. So far so good.
3) Astros provider runs astros and returns output urls using hostname "mstc-astros-pod999" and port 8081 (!!!). 
4) Astros client tries to resolve "http://mstc-astros-pod999:8081/..." input urls and fails - the url is only resolvable from the container with hostname "mstc-astros-pod999" itself.

## Discussion
Due to the fact that a deployment can have multiple pods behind a service, I am having a hard time thinking of a way to define the data service url in a container inside a pod in such a way that another container could reliably access the files inside the exact container/pod. Creating a k8s service for DataService would mean a url (using service name and port) that would be reliable only in the ability to access -- but there is no guarantee the selected pod is the one containing the files we want.

**Comment by dreedyman** [comment]
Your assumption that the pod's URL is not resolvable in a cluster I believe is false. Every service and pod should have a DNS entries created (as described [here](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/). 

A second issue may lie in the fact that the pods are ephemeral, which may be addressed by deploying a `StatefulSet`. This is on my todo list.

**Comment by dreedyman** [comment]
After researching this issue I am going to close it after the following has been verified:

1. In general a pod has the following DNS resolution: `pod-ip-address<.my-namespace.pod.cluster-domain.example.>`
2. The issue as has been reported was the data service was returning a host-name as a way to reconnect.
3. This has been changed to return a formatted url string containing the pod's IP address.

Bringing up another pod in the namespace and verifying that the pod (with data service running) is reachable by it's domain name and data port. Furthermore accessing remote files removes the issue.

Research will continue as to whether a `StatefulSet` is required.

**Comment by marcodlk** [comment]
Thanks for the correction regarding internal pod DNS. I believe the problem with resolving the pod DNS outside the cluster remains, since k8s is designed to expose pods to outside the cluster via a service. Are you able to run the `test_client_with_output_dir` test case on your end?

**Comment by marcodlk** [comment]
FWIW, it is possible to access the pod from outside the cluster with pod name (and port to the desired server) using the apiserver. Whether it is advisable or a good solution is another question...

To download the file "exec-1/out.txt" from pod named "mstc-astros-pod999" via its data service running on port 8081 from host machine (outside cluster):
```
{
APISERVER=$(kubectl config view --minify | grep server | cut -f 2- -d ":" | tr -d " ")
SECRET_NAME=$(kubectl get secrets | grep ^default | cut -f1 -d ' ')
TOKEN=$(kubectl describe secret $SECRET_NAME | grep -E '^token' | cut -f2 -d':' | tr -d " ")

curl $APISERVER/api/v1/namespaces/mstc-dev/pods/mstc-astros-pod999:8081/proxy/exec-1/ \
     --header "Authorization: Bearer $TOKEN" --insecure
}
```
Note that the `--insecure` flag is required, which makes this approach susceptible to MITM attacks; although it may be possible to securely do this with the proper configuration.

If this approach were to be deemed reasonable, we could define a protocol for getting files from an internal data service from an external client using given a url with hostname, port, and file path.

For more on using the apiserver REST API, see [here](https://kubernetes.io/docs/tasks/access-application-cluster/access-cluster/#without-kubectl-proxy). For more on constructing apiserver proxy urls, see [here](https://kubernetes.io/docs/tasks/administer-cluster/access-cluster-services/#manually-constructing-apiserver-proxy-urls).

**Comment by dreedyman** [comment]
I was going to wait until tomorrow, but I'll respond now.

Your issue `I believe the problem with resolving the pod DNS outside the cluster remains`, is not  a valid use-case for us to consider.  The submitting entity (the _driver_) will be deployed to the cluster having access to Kubernetes resources within the cluster. I advise against access to pods from outside the cluster (other than for sanity tests that we use), in any means that does not include an ingress controller with appropriate access permissions. Any results that the _driver_ requires to assemble and make available to outside resources can be done by either a `NodePort` or appropriately configured and deployed ingress controller. 

I'm not sure what use-case you're trying to address here, or if you're just looking for edge cases that need to be documented as to what not to do.

**Comment by marcodlk** [comment]
That makes sense. The context is that I want to integrate this with the tenbar project such that the astros execution is done with the mstc-astros-svc service. If I understand correctly, what we need in this case is a "single run" driver with more or less the following sequence diagram:
![SingleRunDriver_AstrosExec](https://user-images.githubusercontent.com/17425641/150438029-17e688ce-310b-4700-94e4-b3234f50d0a3.png)
The key being that there is a data store, perhaps a StatefulSet, where the output files are collected from inside the cluster and consequently downloaded by the external entity.

**Comment by dreedyman** [comment]
The way I see this working is much simpler. The tenbar script calls the Astros EAP. The EAP gets the input files(s), calls ASTROS, then makes the results returnable in a JSON format.

There is no need for a data store. The Astros EAP pod simply serves up the results (as it does now). Once the results have been fetched we can determine how long to keep them around. I don't see any reason to persist them, it's all ephemeral.

![Untitled](https://user-images.githubusercontent.com/239597/150441649-31ac6005-8287-4e0d-b988-9b01fdefb7c3.png)

**Comment by marcodlk** [comment]
The purpose of the DataStore in my diagram was mostly to serve as a location from where an external client could download the final result files through a service rather than a pod. But I think I follow what you're saying. If I understand, you are proposing that no file URLs are sent in final JSON results. All results that cross the cluster boundary (i.e. from tenbar to client) are JSON data containing just the values the client requested (i.e. area and weight in the tenbar problem). The only file transfers occur within the cluster.

I do prefer not involving a data store if not necessary, simpler the better. Under this design, does the user implement a driver (i.e. the tenbar driver above) deployable to the cluster for each problem (i.e. tenbar)? I think I've been getting caught up thinking that the user would have the option to write a driving script that sits outside the cluster and uses EAPs for remote execution of the eng apps. That is still possible but would be outside of the scope of this project then. That does simplify things.

**Comment by dreedyman** [comment]
Ideally a requesting client will just get back the results as a JSON document. You certainly can get back file URLs as well. As I mentioned above; Any results that the driver (or EAP) requires to assemble and make available to outside resources can be done by either a NodePort or appropriately configured and deployed ingress controller.

This means that yes, an engineer would have the option to write a driving script that sits outside the cluster and uses EAPs for remote execution of the engineering apps. This doesn't mean we need a data store, it just means that we need to deploy and configure the correct Kubernetes resources (ingress controller, load balancer, proxy, etc...) to allow the external script to do that.

Let me try and sum this up:

1. Our first effort should be the tenbar project deployable as a container, be available as a restful web service and accept requests and produce results. I think that provides a reasonable use-case for what we want to accomplish. 
2. We can also provide a test-case that accesses the Astros EAP deployed in a Kubernetes cluster. This is basically what the `integration_test.py::test_client_with_output_dir` does.

This is a good discussion, but it's has gone beyond its title "The current Provider+DataService design may be incompatible with Kubernetes". Maybe we can have a call to discuss.
